-- Run as SYS, SYSTEM, or another DBA account.
-- This creates the Oracle login users used by the C# app.

BEGIN
  EXECUTE IMMEDIATE 'CREATE ROLE admin_role';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1921 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE ROLE entry_role';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1921 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE ROLE viewer_role';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1921 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER upms_admin IDENTIFIED BY admin123 ACCOUNT UNLOCK';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -1920 THEN
    EXECUTE IMMEDIATE 'ALTER USER upms_admin IDENTIFIED BY admin123 ACCOUNT UNLOCK';
  ELSE
    RAISE;
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER upms_operator IDENTIFIED BY operator123 ACCOUNT UNLOCK';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -1920 THEN
    EXECUTE IMMEDIATE 'ALTER USER upms_operator IDENTIFIED BY operator123 ACCOUNT UNLOCK';
  ELSE
    RAISE;
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER upms_auditor IDENTIFIED BY auditor123 ACCOUNT UNLOCK';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -1920 THEN
    EXECUTE IMMEDIATE 'ALTER USER upms_auditor IDENTIFIED BY auditor123 ACCOUNT UNLOCK';
  ELSE
    RAISE;
  END IF;
END;
/

GRANT CREATE SESSION TO admin_role;
GRANT CREATE SESSION TO entry_role;
GRANT CREATE SESSION TO viewer_role;

-- Direct CREATE SESSION grants are included to avoid login problems on stricter Oracle setups.
GRANT CREATE SESSION TO upms_admin;
GRANT CREATE SESSION TO upms_operator;
GRANT CREATE SESSION TO upms_auditor;

GRANT CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER, CREATE SYNONYM TO admin_role;
GRANT admin_role TO upms_admin;
GRANT entry_role TO upms_operator;
GRANT viewer_role TO upms_auditor;

-- Needed so UPMS_ADMIN can create tables without quota errors.
GRANT UNLIMITED TABLESPACE TO upms_admin;

COMMIT;
